[package]
name = "hamlet-client"
version = "0.1.0"
edition = "2024"

[dependencies]
hamlet-protocol = { path = "../protocol" }
gpui-kit = {version = "0.6", "features" = ["inspector"] }
anyhow = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["serde", "std"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
async-channel = "2"
keyring = { version = "=3.0.4", default-features = false, features = ["sync-secret-service"] }

[dev-dependencies]
gpui-kit = { version = "0.6", features = ["test-support"] }
hamlet = { path = "../server" }
actix-web = "4.14"
tempfile = "3"
sea-orm = { version = "=2.0.3", default-features = false, features = ["sqlx-sqlite", "runtime-tokio"] }
