//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub user_id: i64,
    pub channel_id: i64,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub suppress_embeds: bool,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        from = "channel_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub channel: HasOne<super::channel::Entity>,
    #[serde(skip)]
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: HasOne<super::user::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub embeds: HasMany<super::embed::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
