//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub display_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    pub email_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_path: Option<String>,
    pub avatar_updated_at: Option<i64>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub messages: HasMany<super::message::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub reactions: HasMany<super::message_reaction::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub credentials: HasMany<super::credential::Entity>,
    #[serde(skip)]
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::session::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
