[package]
name = "hamlet-protocol"
version = "0.1.0"
edition = "2024"

[features]
openapi = ["dep:utoipa"]

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["serde", "std"] }
utoipa = { version = "5", optional = true, default-features = false, features = ["chrono", "macros"] }

[dev-dependencies]
serde_json = "1"
